// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SnoahRpg.Model;
using System;

namespace SnoahRpg.Migrations
{
    [DbContext(typeof(SnoahRpgContext))]
    [Migration("20170914213210_store")]
    partial class store
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SnoahRpg.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<string>("Power");

                    b.Property<int?>("StoreId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("SnoahRpg.Model.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.Property<string>("Item");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("SnoahRpg.Model.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CurrentChestId");

                    b.Property<int?>("CurrentHelmId");

                    b.Property<int?>("CurrentWeaponId");

                    b.Property<int?>("CurrentWristId");

                    b.Property<int>("Gold");

                    b.Property<int>("Health");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<int>("Power");

                    b.HasKey("Id");

                    b.HasIndex("CurrentChestId");

                    b.HasIndex("CurrentHelmId");

                    b.HasIndex("CurrentWeaponId");

                    b.HasIndex("CurrentWristId");

                    b.ToTable("Monster");
                });

            modelBuilder.Entity("SnoahRpg.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CurrentChestId");

                    b.Property<int>("CurrentHealth");

                    b.Property<int?>("CurrentHelmId");

                    b.Property<int?>("CurrentWeaponId");

                    b.Property<int?>("CurrentWristId");

                    b.Property<int>("Gold");

                    b.Property<int>("MaxHealth");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CurrentChestId");

                    b.HasIndex("CurrentHelmId");

                    b.HasIndex("CurrentWeaponId");

                    b.HasIndex("CurrentWristId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("SnoahRpg.Model.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Gold");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("SnoahRpg.Model.Item", b =>
                {
                    b.HasOne("SnoahRpg.Model.Store")
                        .WithMany("Items")
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("SnoahRpg.Model.Monster", b =>
                {
                    b.HasOne("SnoahRpg.Model.Item", "CurrentChest")
                        .WithMany()
                        .HasForeignKey("CurrentChestId");

                    b.HasOne("SnoahRpg.Model.Item", "CurrentHelm")
                        .WithMany()
                        .HasForeignKey("CurrentHelmId");

                    b.HasOne("SnoahRpg.Model.Item", "CurrentWeapon")
                        .WithMany()
                        .HasForeignKey("CurrentWeaponId");

                    b.HasOne("SnoahRpg.Model.Item", "CurrentWrist")
                        .WithMany()
                        .HasForeignKey("CurrentWristId");
                });

            modelBuilder.Entity("SnoahRpg.Model.Player", b =>
                {
                    b.HasOne("SnoahRpg.Model.Item", "CurrentChest")
                        .WithMany()
                        .HasForeignKey("CurrentChestId");

                    b.HasOne("SnoahRpg.Model.Item", "CurrentHelm")
                        .WithMany()
                        .HasForeignKey("CurrentHelmId");

                    b.HasOne("SnoahRpg.Model.Item", "CurrentWeapon")
                        .WithMany()
                        .HasForeignKey("CurrentWeaponId");

                    b.HasOne("SnoahRpg.Model.Item", "CurrentWrist")
                        .WithMany()
                        .HasForeignKey("CurrentWristId");
                });
#pragma warning restore 612, 618
        }
    }
}
