// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SnoahRpg.Model;
using System;

namespace SnoahRpg.Migrations
{
    [DbContext(typeof(SnoahRpgContext))]
    [Migration("20170913221417_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SnoahRpg.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("LocationId");

                    b.Property<int?>("MonsterId");

                    b.Property<string>("Name");

                    b.Property<int>("Power");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("MonsterId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("SnoahRpg.Model.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("SnoahRpg.Model.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Health");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<int>("Power");

                    b.HasKey("Id");

                    b.ToTable("Monster");
                });

            modelBuilder.Entity("SnoahRpg.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentHealth");

                    b.Property<int?>("CurrentLocationId");

                    b.Property<string>("Image");

                    b.Property<int>("MaxHealth");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("SnoahRpg.Model.PlayerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("PlayerId");

                    b.Property<int>("Power");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerItem");
                });

            modelBuilder.Entity("SnoahRpg.Model.Item", b =>
                {
                    b.HasOne("SnoahRpg.Model.Location")
                        .WithMany("Items")
                        .HasForeignKey("LocationId");

                    b.HasOne("SnoahRpg.Model.Monster")
                        .WithMany("Items")
                        .HasForeignKey("MonsterId");
                });

            modelBuilder.Entity("SnoahRpg.Model.Player", b =>
                {
                    b.HasOne("SnoahRpg.Model.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId");
                });

            modelBuilder.Entity("SnoahRpg.Model.PlayerItem", b =>
                {
                    b.HasOne("SnoahRpg.Model.Player")
                        .WithMany("PlayerItems")
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
